# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl:/zthutest2/
url: http://zhoutong818.github.io
twitter_username:
github_username:

# Build settings
markdown: kramdown
